### PR TITLE
feat(docs): add internationalization and add spanish lang

### PR DESCRIPTION
**Pull request by nelsongutidev**
This PR adds internationalization to the docs site and adds Spanish as the first option for an additional language. 

Internationalization is added following the guidelines on the Starlight official docs. I added a root locale (english) so all links continue to work as they do now. This just sets up everything so additional languages can be added. 

As a part of this work, I translated the main page to Spanish as well as all the guide sections and 2 angular challenges. I can work on the rest of the translations for Spanish if you decide to go forward with this. Please feel free to decline this PR if you decide not to go in this direction, it is completely fine and understandable too.

Starlight is awesome in the sense that untranslated pages will fall back to the English ones so this should be a non-breaking change.

image
image

### CODE REVIEW

**Comment by tomalaforge** [comment]
This is amazing work. 😍 I'll review when I have more time. I'm currently traveling.

**Comment by tomalaforge** [comment]
This is very good work. Thanks a lot. 
The only thing is that I will be unable to maintain it, and when I change something inside a page, it's hard to do the change in all locales. 
But since all translated file are separate files, it's still ok. 

thanks a lot and of course, I will merged it. 👍

**Comment by tomalaforge** [comment]
@all-contributors add @nelsongutidev for doc

**Review by tomalaforge — APPROVED** [review]

**Comment by nelsongutidev** [comment]
> This is very good work. Thanks a lot. The only thing is that I will be unable to maintain it, and when I change something inside a page, it's hard to do the change in all locales. But since all translated file are separate files, it's still ok.
> 
> thanks a lot and of course, I will merged it. 👍

Thanks man! I will do my best to keep it updated with the Spanish version. I have a WIP of the rest of the challenges, a PR should be up soon

**Comment by tomalaforge** [comment]
thanks but be careful because I need to rewrite most of the challenge
documentation. but right now and until end of the year. I don't have a lot
of time.

Challenge without the note at the top should not change. You can start with
these one.

Thanks a lot for doing this. 👍

Le mer. 15 nov. 2023, 22:46, Nelson Gutierrez ***@***.***> a
écrit :

**Pull request merged**
