### PR TITLE
refactor(challenge-1): augment challenge developer experience

### PR DESCRIPTION
**Pull request by kabrunko-dev**
## What this PR is doing

- Create city store
- Add a city image[^1] (credits to @alannelucq; to see image click [here](https://github.com/alannelucq/angular-challenges/blob/56d37c3950363c84ce76d7e6ed4acef8e1fcd098/apps/projection/src/assets/img/city.png))
- Camelcase some student and teacher interfaces' field to remove lint warnings
- Move CardComponent's template to `@Component` decorator to match other components' pattern
- Add new section for bonus challenges

## Checklist for challenge submission

- [ ] Start your PR message with Answer:${challenge_number}

[^1]: This image was chosen by its style similarity with teacher image's style.

### CODE REVIEW

**Comment by tomalaforge** [comment]
Great, I thought you will add some more information inside the documentation page ?

**Comment by kabrunko-dev** [comment]
> Great, I thought you will add some more information inside the documentation page ?

Oh! I did understand that it would be only the code part hahaha I'll try to complement this PR with the documentation part today. If not, I'll make it tomorrow

**Comment by kabrunko-dev** [comment]
New section for bonus challenges added in the challenge documentation 🙋

**Comment by tomalaforge** [comment]
This is very good. Thanks 🙏

**Review by tomalaforge — APPROVED** [review]

**Comment by tomalaforge** [comment]
@kabrunko-dev Do you have a twitter handle ? So I can tag you (If you want)

**Comment by kabrunko-dev** [comment]
> @kabrunko-dev Do you have a twitter handle ? So I can tag you (If you want)

@tomalaforge, I don't have any social media, but I appreciate it 😊

**Comment by tomalaforge** [comment]
@all-contributors add @kabrunko-dev for doc

**Comment by kabrunko-dev** [comment]
> no social media 🥳 well done. Thanks for your work

I'm glad for the oportunity!

**Pull request merged**
