### PR TITLE
Answer:1 answer of projection challenge

### PR DESCRIPTION
**Pull request by tomalaforge**

### CODE REVIEW

**Comment by AshishKumar409** [comment]
Hey! @tomalaforge , I don't think there is any use of card.component.html file as you are using template inside card.component.ts file. or could you please link the card.component.html file

**Comment by tomalaforge** [comment]
Sorry, I didn't understand your question or remark. Can you be more specific?

**Comment by AshishKumar409** [comment]
actually card.component.ts fils has its corresponding template file (card.component.html)  with html code, but still you used the template property inside the card.component.ts to write html.

**Comment by tomalaforge** [comment]
Yes that's true. I updated my solution. I have forgotten to delete the file

**Pull request closed without merging**
