### PR TITLE
Answer:31

### PR DESCRIPTION
**Pull request by nutphi**
## Checklist for challenge submission

- [x] Start your PR message with Answer:31

### CODE REVIEW

**Comment by tomalaforge** [comment]
module should not exist anymore. That's the goal of this challenge

**Comment by nutphi** [comment]
> module should not exist anymore. That's the goal of this challenge

**Comment by nutphi** [comment]
I'm sorry. I closed the PR by mistake. I've updated the fix and removed all modules.

**Comment by tomalaforge** [comment]
Perfect, that's how we do it. Great work

You can use default route to avoid the `_=>_.xxx` but this a preference.

**Pull request closed without merging**
