### PR TITLE
Answer:1

### PR DESCRIPTION
**Pull request by ErickRodrCodes**
## Checklist for challenge submission

- [x] Start your PR message with Answer:${challenge_number}

## Warning:

- If you want feedback or review, you must support the project on GitHub:
  - [$5 per review](https://github.com/sponsors/tomalaforge)
  - [$25 for lifetime reviews](https://github.com/sponsors/tomalaforge)
  - Create one of more challenges
  - Have many valuable contributions to the project

Alternatively, you can still submit your PR to join the list of answered challenges or to be reviewed by a community member. 🔥

### CODE REVIEW

**Comment by boza97** [comment]
You literally copied my answer: https://github.com/tomalaforge/angular-challenges/pull/1039

**Comment by ErickRodrCodes** [comment]
> You literally copied my answer: #1039

oh EXCUSE ME for using prettier. It might like the same, but before I commit, I always run prettier.

Also, you could ask something different like: why did you have a similar approach than mine, let's connect and peer... but no.

**Comment by tomalaforge** [comment]
@boza97 @ErickRodrCodes please be nice to each other.

The goal of the repo is not to fight over a solution but to discuss it. 

@boza97 if someone copied your solution, you should be flattered. It means it's a good might that can inspire others.

**Comment by ErickRodrCodes** [comment]
> @boza97 @ErickRodrCodes please be nice to each other.
> 
> The goal of the repo is not to fight over a solution but to discuss it.
> 
> @boza97 if someone copied your solution, you should be flattered. It means it's a good might that can inspire others.

Totally right on this. My apologies if I used some sarcasm. We should peer and discuss why X solution is better and why it was copied.

TBH, the implementation of a context guard is what took me over @tomalaforge exercise and not @boza97. If something took it personally, I'm not going to entertain that.

**Comment by boza97** [comment]
> > @boza97 @ErickRodrCodes please be nice to each other.
> > The goal of the repo is not to fight over a solution but to discuss it.
> > @boza97 if someone copied your solution, you should be flattered. It means it's a good might that can inspire others.
> 
> Totally right on this. My apologies if I used some sarcasm. We should peer and discuss why X solution is better and why it was copied.
> 
> TBH, the implementation of a context guard is what took me over @tomalaforge exercise and not @boza97. If he took it personally, I'm not going to entertain that.

I am not talking about context guard, but generally store and other things. But as @tomalaforge said i am glad that it inspired you.

**Pull request closed without merging**
