### PR TITLE
Answer:21

### PR DESCRIPTION
**Pull request by BruceArmstrong007**
## Checklist for challenge submission

- [x] Start your PR message with Answer:${challenge_number}

learned fragment method

### CODE REVIEW

**Comment by tomalaforge** [comment]
same here, I think, you have to recheck all your branches. I don't know what happenned but you have some projection code inside all your PR

**Comment by BruceArmstrong007** [comment]
@tomalaforge   (i am doing projections so it will be ingrained into my memory so i can consider it as option for sharable components), 
I will stick to only solving the challenges, my bad ^^' , to keep challenges focused and clean (no additional stuff), it will also be useful for me in future
Thanks for pointing out! im on it

**Comment by BruceArmstrong007** [comment]
@tomalaforge  Removed the Projection extra code, now this commit is clean
i think i have pushed projection initially to main branch of my fork thats the issue

**Comment by BruceArmstrong007** [comment]
@tomalaforge  Removed the Projection extra code, now this commit is clean
i think i have pushed projection initially to main branch of my fork thats the issue

**Pull request closed without merging**
