### PR TITLE
docs: update subscription form component

### PR DESCRIPTION
**Pull request by kabrunko-dev**
Update all i18n to get translated texts for each part of subscription form card

@tomalaforge I did this PR, because I was syncing my repo. However I don't know if what I've done is the best way or you will already deal with the i18n for the component.

Please, let me know If it was already in your roadmap, I'll close this PR.

### CODE REVIEW

**Comment by tomalaforge** [comment]
Amazing, I was going to do it tonight. My daughter woke up so I couldn't finish the task. But I'm very happy to see that you did it. 💪 so fast

**Comment by tomalaforge** [comment]
all-contributors add @kabrunko-dev for code

**Comment by tomalaforge** [comment]
@all-contributors add @kabrunko-dev for code

**Comment by kabrunko-dev** [comment]
> Amazing, I was going to do it tonight. My daughter woke up so I couldn't finish the task. [...]

Hahahah cute.

> [...] But I'm very happy to see that you did it. 💪 so fast

I saw this subscription at the right time and with no task at work. So I thought "Hum.. I'll try it :hand_over_mouth:"

**Review by tomalaforge — APPROVED** [review]

**Pull request merged**
