### PR TITLE
Answer: 39

### PR DESCRIPTION
**Pull request by ygarciavillar**
I like this Angular challenges series. It is a pity that the Angular QA/coding of the past Friday didn't read the README properly, but it is such a great idea this Angular challenge with the Nx repo included. Congrats!.

### CODE REVIEW

**Comment by tomalaforge** [comment]
thanks 😍 and I agree with you, I was so frustrated with the stream of the angular team. I spend a tremendous amount of time creating a documentation 😭

**Comment by tomalaforge** [comment]
Perfect answer, great job 🎉

**Comment by ygarciavillar** [comment]
Yes... I was so frustrating for me too..I couldn't believe it because the documentation is so clear..they only need 5 min or less to read it. But anyway excellent job.

**Comment by tomalaforge** [comment]
Yes thanks for your feedback. But you can see that even the best devs don't know how to read a documentation 😅

**Comment by ygarciavillar** [comment]
Yes, you are right!!🤣🤣

**Pull request closed without merging**
