### PR TITLE
docs(pt): translate challenge 50

### PR DESCRIPTION
**Pull request by kabrunko-dev**

### CODE REVIEW

**Comment by tomalaforge** [comment]
thanks for the translation, but the description will be changed

**Comment by kabrunko-dev** [comment]
> thanks for the translation, but the description will be changed

Oh, that's okay. @tomalaforge do you prefer that I keep open this PR or close it?

**Comment by tomalaforge** [comment]
It's up to you. I don't mind any of both options

**Comment by tomalaforge** [comment]
@kabrunko-dev the description of the challenge is done 👍

**Pull request closed without merging**
