### PR TITLE
Answer:8 pipe solution

### PR DESCRIPTION
**Pull request by ahmed-aouinti**
## Checklist for challenge submission

- [ ] Start your PR message with Answer:${challenge_number}

### CODE REVIEW

**Comment by tomalaforge** [comment]
one PR per challenge please

**Comment by ahmed-aouinti** [comment]
To confirm, should I create three separate pull requests (PRs) titled Answer:8 for the easy, intermediate, and hard pipe solutions?

**Comment by tomalaforge** [comment]
Yes, one PR per challenge with the right answer number. So I can tag them and review them easily

**Comment by ahmed-aouinti** [comment]
done

**Pull request closed without merging**
