### PR TITLE
Answer:31 (Module-to-Standalone)

### PR DESCRIPTION
**Pull request by reed756**
- Refactored app to use standalone components and bootstrapApplication.

### CODE REVIEW

**Comment by tomalaforge** [comment]
Hello @reed756 , is the PR complete ? lots of files are missing

**Comment by reed756** [comment]
Hey @tomalaforge, from the challenge description I wasn't too sure what to do, I refactored the app component to use standalone and also reconfigured the main.ts file to use bootstrapApplication. Were we also supposed to go into the MainShellModule and bring that into the app as standalone components, or something else? Thanks

**Comment by reed756** [comment]
@tomalaforge I have just pushed a commit to update all components in the lib folder to standalone now.

**Comment by tomalaforge** [comment]
That's perfect. 

you can also use the default keyword to avoid using the `then` function inside your import promise

**Pull request closed without merging**
